# Generated by Django 5.2 on 2025-04-09 16:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='question',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='qa.question'),
        ),
    ]
